[emulator]
queued_receipt_state = 8 #ИЗМЕНИТЬ
post_sale = true
flush_receipt = false

[printer]

continuous_mode = true 

[printer.receipt]
eject = true
present_length_mm = 87

[printer.qr]
size=5

[printer.barcode]
impl ='bitImageColumn'

[printer.text]
font='a'
height = 1
width=1
custom_size=false
double_width=false
double_height=false
input = 'cp1251'
output ='cp866'
send_encoding = false

[printer.doc]
font='b'
height = 1
width=1
custom_size=false
double_width=false
double_height=false
input = 'utf8'
output ='cp866'
send_encoding = false
buffer = false

[webkassa]
cassa_unique_number = '' # ЗАПОЛНИтЬ
url = 'http://127.0.0.1:1331/api'
login = '' # ЗАПОЛНИтЬ
password = '' # ЗАПОЛНИтЬ
timeout = 15
attempts = 5

[webkassa.taxgroup]
0 = 0
1 = 0
2 = 12
3 = 20
4 = 25

[webkassa.company]
inn = '' # ЗАПОЛНИтЬ
name = '' # ЗАПОЛНИтЬ

[webkassa.report]
printable = true

[webkassa.receipt]
parse = true 
header = false
regex = '(^Код\W*)(\d+)' #BИЗМЕНИТЬ


