[emulator]
watchdog=true # Общий таймер проверки состояний: смена, токен. Включить -true, выключить - false. 

[emulator.sale]
# Статус Mode(Режим) в случае наличия ошибки при обращении к ЛМ без возможности обработки
gateway_error_state = 8 #ИЗМЕНИТЬ
wait_response = false # false - не ожидать ответ от WebkassaLocal, возвращается стандартный ответ без ошибки, 
                    # true - ожидание ответа от WebkassaLocal

[emulator.shift]
watchdog = true # true - контроль смены включен/false - выключен.
#ВНИМАНИЕ! При отключенном контроле проверка состояния смены (24 часа) не происходит
autoclose = true # включает и отключает автозакрытие true- включено/false - выключено. 
                # В случае  получения статуса 11 от WebkassaLocal при фискализации данных 
                # смена автоматически будет закрыта и фискализация данных продолжится в рамках новой смены
# Тип контроля
close_by=1 # 1 - закрытие по счетчику 24 часа, 2 - закрытие по заданному времени, например 23:59:55
# используется только при параметре close_by = 2
close_at = '23:59:00' # каждый день в 23:59:00

[printer]
[printer.presenter]
# Режим непрерывной презентации документа
continuous = true #ИЗМЕНИТЬ
# eject - выброс чека/документа: true - включен/false - выключен
eject = false #ИЗМЕНИТЬ
# длина выдачи документа из нагубника принтера, действует только в режиме eject=false
present_length_mm = 87

[printer.qr]
# Размер печатаемого QR кода
size=6

[printer.barcode]
# Тип изображение штрихкода. Не менять значнеие по умолчанию
impl ='bitImageColumn'
# Центрирование изображение штрихкода: true - центрировать/false - не центрировать
center=false

[printer.text]
# Настройки относятся к команде 17H
# тип используемого шрифта
font='a'
# высота шрифта
height = 1
# ширина шрифта
width=1
# включить если используются настройки не по умолчанию -> true
custom_size=false
# двойная ширина
double_width=false
# двойная высота
double_height=false
# В случае возникновения ошибок с кодировкой при печати
# изменить атрибуты до нахождения необходимой комбинации
# кодировка в которой передается текст на печать (байты)
input = 'CP1251' #codepage 46
# кодировка при для печати на принтере - соотносится с установкой codepage 
output ='CP866' #codepage 17
# при изменении атрибутов выше, поменять флаг на true
send_encoding = true
# в случае обрыва ленты автоматически печать данные из буфера после восстановления
ensure_printed = true # true- включено, false - отключено
# задержка перед проверкой и ожиданием восстановления
ensure_printed_delay = 0.8


[printer.doc]
# Настройки относятся к печати фискального документа. См. раздел [printer.text]
font='b'
height = 1
width=1
custom_size=true
double_width=false
double_height=false
input = 'utf8'
output ='cp866'
send_encoding = true
ensure_printed = true
ensure_printed_delay = 0.8

[webkassa]
# Авторизационные данные для идентификации кассы при запросах в WebkassaLocal
cassa_unique_number = '' # ЗАПОЛНИТЬ
# В случае установки нескольких серверов или проверки работоспособности изменить на необходимый порт
url = 'http://127.0.0.1:1331/api'
login = 'user@mail.com' # ИЗМЕНИТЬ
password = 'myPassword' # ЗАПОЛНИТЬ
# Время ожидания ответа от WebkassaLocal в секундах
timeout = 6
# Количество попыток получения ответа от WebkassaLocal
attempts = 5

[webkassa.taxgroup]
# таблица соответствия группы налоговой ставки и ее значение в процентах 
0 = 0
1 = 0
2 = 12
3 = 20
4 = 25

[webkassa.company]
# Данные для шапки в фискальных документах. Обязательны к заполнению
inn = '123456789' # ИЗМЕНИТЬ
name = 'ООО "Моя Компания"' # ИЗМЕНИТЬ

[webkassa.token]
# проверка состояния токена (обновление каждые 24 часа)
watchdog = true

[webkassa.report]
# Печать фискальных/нефискальных отчетов true-печтать/false-не печатать
# относится только к Z-отчету
printable = true

[webkassa.receipt]
# Настройки фискального чека
# Поиск кода билета в строке на печать (17H)
parse = true 
# Печать заголовка вендора на чеке
header = false
# Паттерн для поиска кода билета
regex = '(^Код\W*)(\d+)' #ИЗМЕНИТЬ

