[emulator]
watchdog=true # включить -tru, выключить - false. Проверка состояния смены и токена

[emulator.sale]
# Статус Mode(Режим) в случае наличия нефискализированных данных
gateway_error_state = 8 #ИЗМЕНИТЬ
# Алгоритм проведения операции "Закрытие чека"
# Сброс нефискализированных данных в текстовом формате 
flush_receipt = false #ИЗМЕНИТЬ

[emulator.shift]
watchdog = true # true - контроль смены включен/false - выключен.
#ВНИМАНИЕ! При отключенном контроле закрытие смены происходит только при поступлении команды с кассы.
autoclose = true # включает и отключает автозакрытие true- включено/false - выключено
# Тип контроля
close_by=1 # 1' - закрытие по счетчику 24 часа, 2' - закрытие по заданному времени, например 23:59
# используется только при параметре close_by = 2
close_at = '23:59:00' # каждый день в 23:59:00

[printer]
[printer.presenter]
# Режим презентации документа
# Режим непрерывной презентации
continuous = true #ИЗМЕНИТЬ
# eject - выброс: true - включен/false - выключен
eject = false #ИЗМЕНИТЬ
# длина выдачи документа из нагубника принтера, действует только в режиме eject=false
present_length_mm = 87

[printer.qr]
# Размер печатаемого QR кода
size=10

[printer.barcode]
# Тип изображение штрихкода. Не менять значнеие по умолчанию
impl ='bitImageColumn'
# Центрирование изображение штрихкода: true - центрировать/false - не центрировать
center=false

[printer.text]
# Настройки относятся к команде 17H
# тип используемого шрифта
font='a'
# высота шрифта
height = 1
# ширина ihbanf
width=1
# включить если используются настройки не по умолчанию -> true
custom_size=false
# двойная ширина
double_width=false
# двойная высота
double_height=false
# В случае возникновения ошибок с кодировкой при печати
# изменить атрибуты до нахождения необходимой комбинации
# кодировка в которой передается текст на печать (байты)
input = 'CP1251' #codepage 46
# кодировка при для печати на принтере - соотносится с установкой codepage 
output ='CP866' #codepage 17
# при изменении атрибутов выше, поменять флаг на true
send_encoding = false

[printer.doc]
# Настройки относятся к печати фискального документа. См. атрибуты для команды 17H
font='b'
height = 1
width=1
custom_size=true
double_width=false
double_height=false
input = 'utf8'
output ='cp866'
send_encoding = false

[webkassa]
# Авторизационные данные для идентификации кассы при запросах в WebkassaLocal
cassa_unique_number = '' # ЗАПОЛНИТЬ
# В случае установки нескольких серверов или проверки работоспособности изменить на необходимый порт
url = 'http://127.0.0.1:1331/api'
login = '' # ЗАПОЛНИтЬ
password = '' # ЗАПОЛНИтЬ
# Время ожидания ответа от WebkassaLocal в секундах
timeout = 15
# Количество попыток получения ответа от WebkassaLocal в секундах
attempts = 5

[webkassa.taxgroup]
# таблица соответствия группы налоговой ставки и ее значение в процентах 
0 = 0
1 = 0
2 = 12
3 = 20
4 = 25

[webkassa.company]
# Данные для шапки в фискальных документах. Обязательны к заполнению
inn = '' # ЗАПОЛНИТЬ
name = '' # ЗАПОЛНИТЬ

[webkassa.report]
# Печать фискальных/нефискальных отчетов true-печтать/false-не печатать
printable = true

[webkassa.receipt]
# Настройки фискального чека
# Поиск кода билета в строке на печать (17H)
parse = true 
# Печать заголовка вендора на чеке
header = false
# Паттерн для поиска кода билета
regex = '(^Код\W*)(\d+)' #ИЗМЕНИТЬ


